// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type StateAction struct {
	ID        int32        `json:"id"`
	State     string       `json:"state"`
	StepID    int32        `json:"step_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Step struct {
	ID          int32        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Service     string       `json:"service"`
	Topic       string       `json:"topic"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Workflow struct {
	ID          int32        `json:"id"`
	Type        string       `json:"type"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type WorkflowInstance struct {
	ID         string       `json:"id"`
	WorkflowID int32        `json:"workflow_id"`
	Status     string       `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type WorkflowInstanceStep struct {
	ID                 int32          `json:"id"`
	WorkflowInstanceID string         `json:"workflow_instance_id"`
	StepID             int32          `json:"step_id"`
	Status             string         `json:"status"`
	EventMessage       sql.NullString `json:"event_message"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}
