// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process_log.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProcessLog = `-- name: CreateProcessLog :exec
INSERT INTO process_logs (
    event_id,
    workflow_instance_id,
    state,
    status_code,
    status,
    event_message
) VALUES ($1, $2, $3, $4, $5, $6 )
`

type CreateProcessLogParams struct {
	EventID            string        `json:"event_id"`
	WorkflowInstanceID string        `json:"workflow_instance_id"`
	State              string        `json:"state"`
	StatusCode         sql.NullInt32 `json:"status_code"`
	Status             string        `json:"status"`
	EventMessage       string        `json:"event_message"`
}

func (q *Queries) CreateProcessLog(ctx context.Context, arg CreateProcessLogParams) error {
	_, err := q.db.ExecContext(ctx, createProcessLog,
		arg.EventID,
		arg.WorkflowInstanceID,
		arg.State,
		arg.StatusCode,
		arg.Status,
		arg.EventMessage,
	)
	return err
}
