// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateWorkflowInstance(ctx context.Context, arg CreateWorkflowInstanceParams) (WorkflowInstance, error)
	CreateWorkflowInstanceStep(ctx context.Context, arg CreateWorkflowInstanceStepParams) (WorkflowInstanceStep, error)
	FindInstanceStepByID(ctx context.Context, workflowInstanceID string) ([]WorkflowInstanceStep, error)
	FindStepsByState(ctx context.Context, state string) ([]FindStepsByStateRow, error)
	FindWorkflowByType(ctx context.Context, type_ string) (Workflow, error)
	FindWorkflowInstanceByID(ctx context.Context, id string) (WorkflowInstance, error)
}

var _ Querier = (*Queries)(nil)
