// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workflow.sql

package sqlc

import (
	"context"
)

const findWorkflowByType = `-- name: FindWorkflowByType :one
SELECT id, type, description, created_at, updated_at FROM workflows
WHERE type = $1 LIMIT 1
`

func (q *Queries) FindWorkflowByType(ctx context.Context, type_ string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, findWorkflowByType, type_)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
