// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountByID(ctx context.Context, refID string) (int64, error)
	CreateBankAccountRegistration(ctx context.Context, arg CreateBankAccountRegistrationParams) (BankAccountRegistration, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, name string) (User, error)
	FindBankAccountRegistrationByUsernameOrEmail(ctx context.Context, arg FindBankAccountRegistrationByUsernameOrEmailParams) (BankAccountRegistration, error)
	FindOrderByID(ctx context.Context, id int32) (Order, error)
	FindOrderByRefID(ctx context.Context, refID string) (Order, error)
	FindOrdersByUsername(ctx context.Context, username string) ([]Order, error)
	UpdateBankAccountRegistration(ctx context.Context, arg UpdateBankAccountRegistrationParams) (BankAccountRegistration, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
