// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountByID(ctx context.Context, refID string) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	FindOrderByID(ctx context.Context, id int32) (Order, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
